/**
 * ScrollToday Telemetry Engine
 * 
 * A standalone, lightweight tracking engine designed to be bundled directly
 * into creative payloads or loaded as a global script.
 * It manages context (ids), fires 1x1 tracking pixels, and handles viewability
 * and dwell time heartbeats without relying on external libraries like React.
 */

export interface TelemetryConfig {
  trackUrl: string
  creativeId: string
  advertiserId: string
  campaignId?: string
  requestId?: string // Generated by the SDK if not provided by serve-ad
}

export class Telemetry {
  private config: TelemetryConfig
  public readonly requestId: string
  private dwellTimer: number | null = null
  private viewabilityTimer: number | null = null
  private hasTrackedImpression = false
  private hasTrackedViewable = false

  constructor(config: TelemetryConfig) {
    this.config = config
    // Use crypto.randomUUID if available, fallback to Math.random for older environments
    this.requestId =
      config.requestId ||
      (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function'
        ? crypto.randomUUID()
        : Math.random().toString(36).substring(2) + Date.now().toString(36))
  }

  /**
   * Core tracking method. Fires a 1x1 image pixel to the edge function.
   * @param eventType e.g., 'impression_served', 'click', 'engagement'
   * @param extraData Granular format-specific data (e.g., { type: 'flip' })
   */
  public track(_eventType: string, extraData?: Record<string, string | number | boolean>) {
    if (!this.config.trackUrl || !this.config.creativeId || !this.config.advertiserId) {
      console.warn('[ScrollToday SDK] Missing required tracking configuration.')
      return
    }

    let url = `\${this.config.trackUrl}?type=\${encodeURIComponent(eventType)}` +
              `&cid=\${encodeURIComponent(this.config.creativeId)}` +
              `&aid=\${encodeURIComponent(this.config.advertiserId)}` +
              `&rid=\${encodeURIComponent(this.config.requestId!)}` +
              `&cb=\${Date.now()}`

    if (this.config.campaignId) {
      url += `&cmpid=\${encodeURIComponent(this.config.campaignId)}`
    }

    if (extraData) {
      for (const key in extraData) {
        if (Object.prototype.hasOwnProperty.call(extraData, key)) {
          url += `&\${encodeURIComponent(key)}=\${encodeURIComponent(String(extraData[key]))}`
        }
      }
    }

    try {
      const img = new Image()
      img.src = url
    } catch (e) {
      // Fail silently to never interrupt ad rendering
    }
  }

  /**
   * Initializes standard tracking: impression, initial presence, and heartbeat.
   * Should be called immediately after the creative mounts.
   */
  public initStandardTracking() {
    if (!this.hasTrackedImpression) {
      this.track('impression_served')
      this.hasTrackedImpression = true
      
      // Initial presence hit so Avg Dwell is not 0 for short views
      this.track('presence', { dwell_time_ms: 1000 })
    }

    this.startDwellHeartbeat()
    this.startViewabilityMonitor()
  }

  /**
   * Dwell Time Heartbeat
   * Every 5 seconds of active presence, fire a presence event.
   */
  private startDwellHeartbeat() {
    if (this.dwellTimer) clearInterval(this.dwellTimer)
    
    // In a browser environment, use setInterval
    if (typeof window !== 'undefined' && typeof document !== 'undefined') {
      this.dwellTimer = window.setInterval(() => {
        // Only track if tab is active (not hidden)
        if (!document.hidden) {
          this.track('presence', { dwell_time_ms: 5000 })
        }
      }, 5000)
    }
  }

  /**
   * Basic viewability monitor using IntersectionObserver.
   * Fires 'impression_viewable' when >= 50% in view for > 1 second.
   */
  private startViewabilityMonitor() {
    if (this.hasTrackedViewable) return
    if (typeof window === 'undefined' || typeof IntersectionObserver === 'undefined') return

    let viewTimer: number | null = null

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            // Start 1s timer when in view
            if (!viewTimer) {
              viewTimer = window.setTimeout(() => {
                if (!this.hasTrackedViewable) {
                  this.track('impression_viewable')
                  this.hasTrackedViewable = true
                  observer.disconnect() // Stop monitoring once tracked
                }
              }, 1000)
            }
          } else {
            // Cancel timer if it goes out of view before 1s
            if (viewTimer) {
              clearTimeout(viewTimer)
              viewTimer = null
            }
          }
        })
      },
      { threshold: 0.5 } // 50% visible
    )

    // Observe the body or root creative container
    const root = document.getElementById('creative-root') || document.body
    if (root) observer.observe(root)
  }

  /**
   * Clean up timers and observers (useful for single-page app transitions or editor preview)
   */
  public destroy() {
    if (this.dwellTimer) {
      clearInterval(this.dwellTimer)
      this.dwellTimer = null
    }
    if (this.viewabilityTimer) {
      clearTimeout(this.viewabilityTimer)
      this.viewabilityTimer = null
    }
  }
}

// Allow global access if bundled into a script tag
if (typeof window !== 'undefined') {
  ;(window as any).ScrollTodaySDK = {
    Telemetry,
  }
}
