/**
 * ScrollToday Database Types
 *
 * Generated from Supabase schema on 2026-02-19.
 * This file will be auto-regenerated by `supabase gen types typescript` when
 * Docker is available, or via CI/CD pipeline.
 *
 * Location: packages/shared/src/database.types.ts
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      ad_events: {
        Row: {
          advertiser_id: string
          campaign_id: string | null
          created_at: string
          creative_id: string
          event_timestamp: string
          event_type: Database["public"]["Enums"]["event_type"]
          extra_data: Json | null
          id: string
          request_id: string
        }
        Insert: {
          advertiser_id: string
          campaign_id?: string | null
          created_at?: string
          creative_id: string
          event_timestamp?: string
          event_type: Database["public"]["Enums"]["event_type"]
          extra_data?: Json | null
          id?: string
          request_id: string
        }
        Update: {
          advertiser_id?: string
          campaign_id?: string | null
          created_at?: string
          creative_id?: string
          event_timestamp?: string
          event_type?: Database["public"]["Enums"]["event_type"]
          extra_data?: Json | null
          id?: string
          request_id?: string
        }
        Relationships: []
      }
      credit_transactions: {
        Row: {
          id: string
          advertiser_id: string
          type: string // 'purchase' | 'adjustment' | 'refund'
          amount: number
          balance_after: number | null
          stripe_session_id: string | null
          stripe_payment_intent_id: string | null
          receipt_url: string | null
          metadata: Json
          created_at: string
        }
        Insert: {
          advertiser_id: string
          type: string // 'purchase' | 'adjustment' | 'refund'
          amount: number
          balance_after?: number | null
          stripe_session_id?: string | null
          stripe_payment_intent_id?: string | null
          receipt_url?: string | null
          metadata?: Json
          id?: string
          created_at?: string
        }
        Update: {
          id?: string
          advertiser_id?: string
          type?: string
          amount?: number
          balance_after?: number | null
          stripe_session_id?: string | null
          stripe_payment_intent_id?: string | null
          receipt_url?: string | null
          metadata?: Json
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "credit_transactions_advertiser_id_fkey"
            columns: ["advertiser_id"]
            isOneToOne: false
            referencedRelation: "advertisers"
            referencedColumns: ["id"]
          },
        ]
      }
      advertisers: {
        Row: {
          contact_email: string | null
          created_at: string
          credit_balance: number
          id: string
          name: string
          updated_at: string
        }
        Insert: {
          contact_email?: string | null
          created_at?: string
          credit_balance?: number
          id?: string
          name: string
          updated_at?: string
        }
        Update: {
          contact_email?: string | null
          created_at?: string
          credit_balance?: number
          id?: string
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      campaigns: {
        Row: {
          advertiser_id: string
          created_at: string
          id: string
          name: string
          status: Database["public"]["Enums"]["campaign_status"]
          updated_at: string
          advertiser_name: string | null
          start_date: string | null
          end_date: string | null
        }
        Insert: {
          advertiser_id: string
          created_at?: string
          id?: string
          name: string
          status?: Database["public"]["Enums"]["campaign_status"]
          updated_at?: string
          advertiser_name?: string | null
          start_date?: string | null
          end_date?: string | null
        }
        Update: {
          advertiser_id?: string
          created_at?: string
          id?: string
          name?: string
          status?: Database["public"]["Enums"]["campaign_status"]
          updated_at?: string
          advertiser_name?: string | null
          start_date?: string | null
          end_date?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "campaigns_advertiser_id_fkey"
            columns: ["advertiser_id"]
            isOneToOne: false
            referencedRelation: "advertisers"
            referencedColumns: ["id"]
          },
        ]
      }
      creative_trackers: {
        Row: {
          id: string
          creative_id: string
          tracker_config_id: string
          fire_condition: string // 'on_load' | 'on_viewable' | 'on_click' | 'on_engagement'
          created_at: string
        }
        Insert: {
          creative_id: string
          tracker_config_id: string
          fire_condition: string // 'on_load' | 'on_viewable' | 'on_click' | 'on_engagement'
          id?: string
          created_at?: string
        }
        Update: {
          id?: string
          creative_id?: string
          tracker_config_id?: string
          fire_condition?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "creative_trackers_creative_id_fkey"
            columns: ["creative_id"]
            isOneToOne: false
            referencedRelation: "creatives"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "creative_trackers_tracker_config_id_fkey"
            columns: ["tracker_config_id"]
            isOneToOne: false
            referencedRelation: "tracker_configs"
            referencedColumns: ["id"]
          },
        ]
      }
      creatives: {
        Row: {
          advertiser_id: string
          bundle_url: string | null
          campaign_id: string | null
          created_at: string
          deleted_at: string | null
          format_id: string
          format_name: string
          height: number | null
          id: string
          name: string
          preview_token: string | null
          rendered_html: string | null
          schema_version: number
          status: Database["public"]["Enums"]["creative_status"]
          template_data: Json
          thumbnail_url: string | null
          updated_at: string
          width: number | null
        }
        Insert: {
          advertiser_id: string
          bundle_url?: string | null
          campaign_id?: string | null
          created_at?: string
          deleted_at?: string | null
          format_id: string
          format_name: string
          height?: number | null
          id?: string
          name: string
          preview_token?: string | null
          rendered_html?: string | null
          schema_version?: number
          status?: Database["public"]["Enums"]["creative_status"]
          template_data?: Json
          thumbnail_url?: string | null
          updated_at?: string
          width?: number | null
        }
        Update: {
          advertiser_id?: string
          bundle_url?: string | null
          campaign_id?: string | null
          created_at?: string
          deleted_at?: string | null
          format_id?: string
          format_name?: string
          height?: number | null
          id?: string
          name?: string
          preview_token?: string | null
          rendered_html?: string | null
          schema_version?: number
          status?: Database["public"]["Enums"]["creative_status"]
          template_data?: Json
          thumbnail_url?: string | null
          updated_at?: string
          width?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "creatives_advertiser_id_fkey"
            columns: ["advertiser_id"]
            isOneToOne: false
            referencedRelation: "advertisers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "creatives_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      daily_metrics: {
        Row: {
          advertiser_id: string
          campaign_id: string | null
          clicks: number
          created_at: string
          creative_id: string | null
          engagements: number
          id: string
          impressions_served: number
          impressions_viewable: number
          metric_date: string
          total_dwell_time_ms: number
          updated_at: string
          video_completes: number
          video_plays: number
        }
        Insert: {
          advertiser_id: string
          campaign_id?: string | null
          clicks?: number
          created_at?: string
          creative_id?: string | null
          engagements?: number
          id?: string
          impressions_served?: number
          impressions_viewable?: number
          metric_date: string
          total_dwell_time_ms?: number
          updated_at?: string
          video_completes?: number
          video_plays?: number
        }
        Update: {
          advertiser_id?: string
          campaign_id?: string | null
          clicks?: number
          created_at?: string
          creative_id?: string | null
          engagements?: number
          id?: string
          impressions_served?: number
          impressions_viewable?: number
          metric_date?: string
          total_dwell_time_ms?: number
          updated_at?: string
          video_completes?: number
          video_plays?: number
        }
        Relationships: [
          {
            foreignKeyName: "daily_metrics_advertiser_id_fkey"
            columns: ["advertiser_id"]
            isOneToOne: false
            referencedRelation: "advertisers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "daily_metrics_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "daily_metrics_creative_id_fkey"
            columns: ["creative_id"]
            isOneToOne: false
            referencedRelation: "creatives"
            referencedColumns: ["id"]
          },
        ]
      }
      tracker_configs: {
        Row: {
          id: string
          advertiser_id: string
          name: string
          tracker_url: string
          tracker_type: string // 'pixel' | 'script'
          created_at: string
          updated_at: string
          category: string // 'conversion' | 'impression' | 'click'
        }
        Insert: {
          advertiser_id: string
          name: string
          tracker_url: string
          tracker_type: string // 'pixel' | 'script'
          id?: string
          created_at?: string
          updated_at?: string
          category?: string // defaults to 'impression'
        }
        Update: {
          id?: string
          advertiser_id?: string
          name?: string
          tracker_url?: string
          tracker_type?: string
          created_at?: string
          updated_at?: string
          category?: string
        }
        Relationships: [
          {
            foreignKeyName: "tracker_configs_advertiser_id_fkey"
            columns: ["advertiser_id"]
            isOneToOne: false
            referencedRelation: "advertisers"
            referencedColumns: ["id"]
          },
        ]
      }
      user_profiles: {
        Row: {
          advertiser_id: string | null
          auth_user_id: string
          created_at: string
          display_name: string | null
          id: string
          must_change_password: boolean
          role: Database["public"]["Enums"]["user_role"]
          updated_at: string
        }
        Insert: {
          advertiser_id?: string | null
          auth_user_id: string
          created_at?: string
          display_name?: string | null
          id?: string
          must_change_password?: boolean
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
        }
        Update: {
          advertiser_id?: string | null
          auth_user_id?: string
          created_at?: string
          display_name?: string | null
          id?: string
          must_change_password?: boolean
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_profiles_advertiser_id_fkey"
            columns: ["advertiser_id"]
            isOneToOne: false
            referencedRelation: "advertisers"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      add_impression_credits: {
        Args: { p_advertiser_id: string; p_amount: number }
        Returns: number
      }
      deduct_impression_credit: {
        Args: { p_advertiser_id: string }
        Returns: boolean
      }
      rollup_daily_metrics: {
        Args: { p_date: string }
        Returns: number
      }
      rollup_today_metrics: {
        Args: { p_advertiser_id: string }
        Returns: number
      }
      get_user_advertiser_id: {
        Args: Record<PropertyKey, never>
        Returns: string
      }
      is_super_admin: {
        Args: Record<PropertyKey, never>
        Returns: boolean
      }
    }
    Enums: {
      campaign_status: "draft" | "active" | "paused" | "completed"
      creative_status: "draft" | "active" | "paused" | "archived"
      event_type:
        | "impression_served"
        | "impression_viewable"
        | "engagement"
        | "click"
        | "video_play"
        | "video_pause"
        | "video_complete"
        | "expand"
        | "collapse"
        | "close"
      user_role: "super_admin" | "advertiser"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Convenience type aliases
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"]
export type Insertable<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"]
export type Updatable<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"]
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T]
