-- =============================================================================
-- Phase 8: Ad Serving Infrastructure - Foundation Migration
-- =============================================================================
-- Adds credit_balance to advertisers, rendered_html to creatives,
-- creates deduct_impression_credit atomic function, and partial index
-- =============================================================================

-- 1. Add credit_balance column to advertisers
-- Default 0 means no credits purchased yet. BIGINT supports billions of impressions.
ALTER TABLE public.advertisers
  ADD COLUMN IF NOT EXISTS credit_balance BIGINT NOT NULL DEFAULT 0;

-- 2. Add rendered_html column to creatives
-- Stores the complete HTML document generated by buildPreviewHtml() at save time.
-- Used by serve-ad Edge Function to avoid duplicating renderer code in Deno runtime.
ALTER TABLE public.creatives
  ADD COLUMN IF NOT EXISTS rendered_html TEXT;

COMMENT ON COLUMN public.creatives.rendered_html IS
  'Pre-rendered HTML generated by buildPreviewHtml() at save time. Used by serve-ad Edge Function to avoid duplicating renderer code in Deno runtime.';

-- 3. Partial index for fast credit balance lookup during ad serving
-- Only indexes advertisers with positive balance (the ones actively serving ads)
CREATE INDEX IF NOT EXISTS idx_advertisers_credit_balance
  ON public.advertisers (id) WHERE credit_balance > 0;

-- 4. Atomic credit deduction function
-- Uses PostgreSQL implicit row-level lock during UPDATE to prevent concurrent
-- over-deduction. FOUND is true only if a row was updated (balance was >= 1).
CREATE OR REPLACE FUNCTION public.deduct_impression_credit(p_advertiser_id UUID)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.advertisers
  SET credit_balance = credit_balance - 1,
      updated_at = now()
  WHERE id = p_advertiser_id
    AND credit_balance >= 1;

  RETURN FOUND;
END;
$$;

COMMENT ON FUNCTION public.deduct_impression_credit IS
  'Atomically deducts one impression credit. Returns FALSE if balance is zero (ads should stop serving). Uses implicit row-level lock to prevent concurrent over-deduction.';
